version: "3.7"
services:
  #
  # DATABASES
  #
  user-db:
    image: postgres
    environment:
      POSTGRES_DB: user-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - db-network
  movie-db:
    image: postgres
    environment:
      POSTGRES_DB: movie-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - db-network
  comment-db:
    image: postgres
    environment:
      POSTGRES_DB: comment-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5434:5432"
    restart: unless-stopped
    networks:
      - db-network
  series-db:
    image: postgres
    environment:
      POSTGRES_DB: series-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5435:5432"
    restart: unless-stopped
    networks:
      - db-network
  rating-db:
    image: postgres
    environment:
      POSTGRES_DB: rating-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5436:5432"
    restart: unless-stopped
    networks:
      - db-network
  metadata-db:
    image: postgres
    environment:
      POSTGRES_DB: metadata-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5437:5432"
    restart: unless-stopped
    networks:
        - db-network
  favorite-db:
    image: postgres
    environment:
      POSTGRES_DB: favorite-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5438:5432"
    restart: unless-stopped
    networks:
      - db-network

  #
  # MICROSERVICES
  #
  config-server:
    image: eacoursemiu/config-server:0.0.1
    ports:
      - "4040:4040"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8888/eureka
      - spring.cloud.config.server.vault.host=vault-server
      - spring.zipkin.base-url=http://zipkin:9411
    depends_on:
      - service-discovery
    networks:
      - microservice-network

  service-discovery:
    image: eacoursemiu/service-discovery:0.0.1
    ports:
      - "8888:8888"
    depends_on:
      - zipkin
    networks:
      - microservice-network

  api-gateway:
    image: eacoursemiu/api-gateway:0.0.1
    ports:
      - "8889:8889"
    environment:
      - spring.zipkin.base-url=http://zipkin:9411
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8888/eureka
      - app.config.keycloak.url=http://keycloak:8080
    depends_on:
      - config-server
      - service-discovery
    networks:
      - microservice-network

  user-service:
    image: eacoursemiu/user-service:0.0.1
    container_name: user-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8888/eureka
      - spring.config.import=optional:configserver:http://config-server:4040
      - spring.zipkin.base-url=http://zipkin:9411
      - spring.datasource.url=jdbc:postgresql://user-db:5432/user-db
    depends_on:
      - config-server
      - service-discovery
      - user-db
    networks:
      - microservice-network
      - db-network
    restart: unless-stopped

  movie-service:
    image: eacoursemiu/movie-service:0.0.1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8888/eureka
      - spring.config.import=optional:configserver:http://config-server:4040
      - spring.zipkin.base-url=http://zipkin:9411
      - spring.datasource.url=jdbc:postgresql://movie-db:5432/movie-db
    depends_on:
      - config-server
      - service-discovery
      - movie-db
    networks:
      - microservice-network
      - db-network

  comment-service:
    image: eacoursemiu/comment-service:0.0.1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8888/eureka
      - spring.config.import=optional:configserver:http://config-server:4040
      - spring.zipkin.base-url=http://zipkin:9411
      - spring.datasource.url=jdbc:postgresql://comment-db:5432/comment-db
    depends_on:
      - config-server
      - service-discovery
      - comment-db
    networks:
      - microservice-network
      - db-network
    restart: unless-stopped

  series-service:
    image: eacoursemiu/series-service:0.0.1
    depends_on:
      - config-server
      - service-discovery
      - series-db
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8888/eureka
      - spring.config.import=optional:configserver:http://config-server:4040
      - spring.zipkin.base-url=http://zipkin:9411
      - spring.datasource.url=jdbc:postgresql://series-db:5432/series-db
    networks:
      - microservice-network
      - db-network

  rating-service:
    image: eacoursemiu/rating-service:0.0.1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8888/eureka
      - spring.config.import=optional:configserver:http://config-server:4040
      - spring.zipkin.base-url=http://zipkin:9411
      - spring.datasource.url=jdbc:postgresql://rating-db:5432/rating-db
    depends_on:
      - config-server
      - service-discovery
      - rating-db
    networks:
      - microservice-network
      - db-network
    restart: unless-stopped

  metadata-service:
    image: eacoursemiu/metadata-service:0.0.1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8888/eureka
      - spring.config.import=optional:configserver:http://config-server:4040
      - spring.zipkin.base-url=http://zipkin:9411
      - spring.datasource.url=jdbc:postgresql://metadata-db:5432/metadata-db
    depends_on:
      - config-server
      - service-discovery
      - metadata-db
    networks:
      - microservice-network
      - db-network
    restart: unless-stopped

  favorite-service:
    image: eacoursemiu/favorite-service:0.0.1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8888/eureka
      - spring.config.import=optional:configserver:http://config-server:4040
      - spring.zipkin.base-url=http://zipkin:9411
      - spring.datasource.url=jdbc:postgresql://favorite-db:5432/favorite-db
    depends_on:
      - config-server
      - service-discovery
      - favorite-db
    networks:
      - microservice-network
      - db-network

  #
  # ZIPKIN
  #
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  #
  # MESSAGING
  #
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservice-network

  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - microservice-network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    restart: unless-stopped
    networks:
      - microservice-network


  #
  # KEYCLAOK
  #
  keycloak:
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: quay.io/keycloak/keycloak:20.0.1
    ports:
      - "8080:8080"
    command:
      - "start-dev"
    restart: unless-stopped
    networks:
      - microservice-network

  #
  # VAULT
  #
  vault-server:
    image: vault:latest
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"
    networks:
      - microservice-network

#
# NETWORKS
#

networks:
  db-network:
  zipkin-network:
  microservice-network: