apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-app
data:
  init_data.sql: |
      
    CREATE SCHEMA comment-db
    USE SCHEMA `comment-db`
    
    CREATE TYPE MediaType AS ENUM('MOVIE','TV','SEASON','EPISODE');

    CREATE TABLE IF NOT EXISTS Comment(
      ID SERIAL PRIMARY KEY NOT NULL AUTO_INCREMENT,
      comment VARCHAR(280) DEFAULT NULL,
      createdDate DATE DEFAULT NULL,
      mediaId INTEGER NOT NULL,
      mediaType MediaType,
      updateDate DATE,
      userId VARCHAR(100));

    insert into comment(id,comment,created_date,media_id,media_type,update_date,user_id)
    values(1,'Wonderful','02/22/2022',1,'MOVIE','02/22/2022',1),(2,'Nice','02/22/2022',2,'SEASON','02/22/2022',2),(3,'Best Season','03/22/2022',1,'SEASON','03/22/2022',2),(4,'Fantasy Movie','05/22/2022',2,'MOVIE','05/22/2022',1);
  
    CREATE SCHEMA metadata-db
    SET SCHEMA 'metadata-db'
  
    CREATE TABLE IF NOT EXISTS Genre(
      ID SERIAL PRIMARY KEY,
      name VARCHAR(280));
  
    insert into genre  (id,name)
    values (1,'Action'),(2,'Drama'),(3,'Comedy'),(4,'Crime'),(5,'Animation'),(6,'SuperHero');
  
    CREATE TABLE IF NOT EXISTS Person(
      ID SERIAL PRIMARY KEY,
      name VARCHAR(280));
  
    insert into person (id,name)
    values (1,'Alex'),(2,'Alex2'),(3,'Alex3'),(4,'Alex4'),(5,'Alex5');
  
    CREATE TABLE IF NOT EXISTS Position(
      ID SERIAL PRIMARY KEY,
      title VARCHAR(280));
  
    insert into position (id,title,person_id)
    values (1,'director',1),(2,'Actor',1),(3,'director',2),(4,'Actor',3),(5,'director',4);
