server:
  port: 7072

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  application:
    name: movie-service
  datasource:
    password: 1
    username: postgres
    url: jdbc:postgresql://localhost:5434/movie-db
  sql:
    init:
      mode: always

  kafka:
    consumer:
      group-id: ea_group_8
      auto-offset-reset: earliest
    bootstrap-servers: http://localhost:9092

  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      registerWithEureka: true
      defaultZone: http://localhost:8888/eureka/
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

keycloak:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkMjKgPrcd9RUBPhS42SQ6SqXQrk44aTUQUvekOe/O6TSW5InzVgc5ZY0XC7ENcfshsE/E8nIb6L5qaJ7H9k13BjVsLtcblRg6bMPGmX4DtyWwauVgtcDr7Hqb6XexiPfahpxOKP9xV/KDDvMfX4j/tXgR2rDeR/kKF+0vNE6tCReBhdyIwYZPdzRC9aIJtx6CezJx1TK7kD48XBm5j/DzsnQfJYMKZlNKzmdzdPEouRY+ZWeHT2otDxCGaeLNMa/uApkd8+2exMAQucXwjDS0vnUGF3VP5A06p6mCGAxvKhFrw5gLpx4e+fFidqKModavz/xEkriEJ+nydxL72C6+QIDAQAB
