server:
  port: 7072

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  application:
    name: movie-service
  datasource:
    password: 123456
    username: postgres
    url: jdbc:postgresql://localhost:5434/movie-db
  sql:
    init:
      mode: always

  kafka:
    consumer:
      group-id: ea_group_8
      auto-offset-reset: earliest
    bootstrap-servers: http://localhost:29092

  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      registerWithEureka: true
      defaultZone: http://localhost:8888/eureka/
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
