apiVersion: v1
kind: Service
metadata:
  name: comment-service
  labels:
    app: comment-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081
  selector:
    app: comment-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
  labels:
    app: comment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: comment-service
          image: kelvinus2022/comment-service:1.0.1
#          imagePullPolicy: Never

#          configmap
#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: "prod"
#            - name: ACCOUNT_SERVICE_SECRET_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: service-secret
#                  key: account-service-secret-key
          ports:
            - name: http
              containerPort: 8080
# Kubernetes check health service
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080