apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  labels:
    app: metadata-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80
      nodePort: 30083
  selector:
    app: metadata-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
  labels:
    app: metadata-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
    spec:
      containers:
        - name: metadata-service
          image: kelvinus2022/metadata-service:1.0.0
          ports:
            - name: http
              containerPort: 80
