apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  labels:
    app: service-discovery
spec:
  ports:
    - name: http
      port: 8888
      targetPort: 80
      nodePort: 30083
  selector:
    app: service-discovery
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  labels:
    app: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
        - name: service-discovery
          image: kelvinus2022/service-discovery:1.0.0
#          imagePullPolicy: Never

#          configmap
#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: "prod"
#            - name: ACCOUNT_SERVICE_SECRET_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: service-secret
#                  key: account-service-secret-key
          ports:
            - name: http
              containerPort: 80
# Kubernetes check health service
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080