spring:
  profiles:
    active: vault, git
  cloud:
    config:
      server:
        vault:
          order: 1
          host: 127.0.0.1
          port: 8200
          authentication: TOKEN
          token: 00000000-0000-0000-0000-000000000000
          scheme: http
          kv-version: 2
        git:
          order: 2
          skip-ssl-validation: true
          clone-on-start: true
          uri: https://github.com/EA-course-MIU/config-repo
          default-label: main
          search-paths: config
    service-registry:
      auto-registration:
        enabled: true
    discovery:
      enabled: true
  application:
    name: config-service
  zipkin:
    base-url: http://localhost:9411
management:
  health:
    livenessstate:
        enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, env
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      registerWithEureka: true
      defaultZone: http://localhost:8888/eureka
    enabled: true
server:
  port: 4040
